/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const YesnoLazyImport = createFileRoute('/yesno')()
const SaccadesLazyImport = createFileRoute('/saccades')()
const PursuitLazyImport = createFileRoute('/pursuit')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const YesnoLazyRoute = YesnoLazyImport.update({
  path: '/yesno',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/yesno.lazy').then((d) => d.Route))

const SaccadesLazyRoute = SaccadesLazyImport.update({
  path: '/saccades',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/saccades.lazy').then((d) => d.Route))

const PursuitLazyRoute = PursuitLazyImport.update({
  path: '/pursuit',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pursuit.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/pursuit': {
      preLoaderRoute: typeof PursuitLazyImport
      parentRoute: typeof rootRoute
    }
    '/saccades': {
      preLoaderRoute: typeof SaccadesLazyImport
      parentRoute: typeof rootRoute
    }
    '/yesno': {
      preLoaderRoute: typeof YesnoLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  PursuitLazyRoute,
  SaccadesLazyRoute,
  YesnoLazyRoute,
])

/* prettier-ignore-end */
